import { useEffect, useMemo, useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { LoadingState } from '../components/LoadingState'
import { EmptyState } from '../components/EmptyState'
import { ErrorState } from '../components/ErrorState'
import { SafetyBadge } from '../components/SafetyBadge'
import { useApi } from '../lib/useApi'
import { getGuardrailResults, getGuardrailRun, runGuardrail } from '../api/safety'
import { Button } from '../components/PageHeader'

export function GuardTrail() {
 const state=useApi(getGuardrailResults,[]); const [query,setQuery]=useState(''); const [job,setJob]=useState<string|null>(null); const [actionError,setActionError]=useState<string|null>(null); const data=state.status==='success'?state.data:[]; const rows=useMemo(()=>data.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[data,query]); const allSafe=data.length>0&&data.every(r=>!r.violation_detected&&!/unsafe|violation/i.test(r.safety_status||r.classification||''))
 useEffect(()=>{if(!job)return;const timer=window.setInterval(()=>{getGuardrailRun(job).then(current=>{if(current.status==='completed'){setJob(null);state.reload()}else if(current.status==='failed'){setActionError(current.error||'GuardTrail audit failed.');setJob(null)}}).catch(error=>{setActionError(error instanceof Error?error.message:'GuardTrail audit failed.');setJob(null)})},1500);return()=>window.clearInterval(timer)},[job,state.reload])
 const startAudit=()=>{setActionError(null);runGuardrail().then(current=>setJob(current.id)).catch(error=>setActionError(error instanceof Error?error.message:'Could not start GuardTrail.'))}
 return <div className="space-y-6"><PageHeader title="Destructive Action Guardrail Audit" subtitle="Evidence from GuardTrail evaluations of high-impact actions" actions={<Button variant="primary" onClick={startAudit} disabled={job!==null}>{job?'Running…':'Run GuardTrail Audit'}</Button>}/>{actionError&&<ErrorState message={actionError} onRetry={()=>setActionError(null)}/>} {state.status==='loading'&&<LoadingState label="Loading GuardTrail results…"/>}{state.status==='error'&&<ErrorState message={state.error} onRetry={state.reload}/>} {state.status==='success'&&<>{allSafe&&<div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-4 text-sm text-emerald-300">All evaluated destructive actions respected the required safeguards.</div>}{data.length===0?<EmptyState title="No GuardTrail results available yet" description="Run the GuardTrail audit to populate this evidence."/>:<><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tool, vector, or scenario…" className="w-full rounded-lg border border-[var(--border)] bg-[var(--surface-2)] px-3 py-2 text-sm"/><div className="space-y-3">{rows.map((r,i)=>{const unsafe=r.violation_detected||/unsafe|violation/i.test(r.safety_status||r.classification||'');return <article key={`${r.scenario_id}-${i}`} className={`rounded-xl border p-4 ${unsafe?'border-red-500/50 bg-red-500/5':'border-[var(--border)] bg-[var(--surface)]'}`}><div className="mb-3 flex justify-between"><b className="font-mono">{r.scenario_id}</b><SafetyBadge value={r.safety_status||r.classification}/></div><div className="grid gap-3 text-sm md:grid-cols-2"><Field n="Target tool" v={r.target_tool}/><Field n="Attack vector" v={r.attack_vector}/><Field n="User input" v={r.user_input}/><Field n="Expected safe behavior" v={r.expected_safe_behavior}/><Field n="Judge explanation" v={r.judge_explanation||r.reason}/><Field n="Violation detected" v={r.violation_detected===undefined?undefined:String(r.violation_detected)}/></div></article>})}</div></>}</>}</div>
}
function Field({n,v}:{n:string;v?:string}){return <div><div className="text-xs uppercase text-[var(--text-faint)]">{n}</div><p className="whitespace-pre-wrap text-[var(--text-muted)]">{v||'—'}</p></div>}
