import { useParams } from 'react-router-dom'
import { useState } from 'react'
import { PageHeader } from '../components/PageHeader'
import { LoadingState } from '../components/LoadingState'
import { ErrorState } from '../components/ErrorState'
import { SafetyBadge } from '../components/SafetyBadge'
import { useApi } from '../lib/useApi'
import { generatePatch, getPatch, getPatchResult, retestPatch } from '../api/safety'

export function ExistingPatches() { const {id=''}=useParams(); const patch=useApi(()=>getPatch(id),[id]); const result=useApi(()=>getPatchResult(id),[id]); if(patch.status==='loading'||result.status==='loading')return <LoadingState label="Loading remediation evidence…"/>; if(patch.status==='error')return <ErrorState message={patch.error} onRetry={patch.reload}/>; if(result.status==='error')return <ErrorState message={result.error} onRetry={result.reload}/>; const p=patch.data,r=result.data; return <div className="space-y-6"><PageHeader title="Auto-Fix / Prompt Patcher" subtitle={`Remediation evidence for ${id}`}/><section className="rounded-xl border border-red-500/30 bg-red-500/5 p-5"><h2 className="font-semibold">Failure</h2><div className="mt-2 flex gap-2"><SafetyBadge value={r.before?.classification}/><SafetyBadge value={p.severity||r.before?.severity}/><span>Failed turn: {p.failed_turn??r.before?.failed_turn??'—'}</span></div><p className="mt-3 text-sm text-[var(--text-muted)]">{p.reason||r.before?.reason||'No failure rationale returned.'}</p></section><section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Generated patch</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{p.vulnerability_analysis||'No vulnerability analysis returned.'}</p><p className="mt-2 text-sm text-[var(--text-muted)]">{p.patch_summary||'No patch summary returned.'}</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><Prompt title="Original prompt" value={p.original_prompt}/><Prompt title="Patched prompt" value={p.patched_prompt}/></div>{p.unified_diff&&<pre className="mt-4 overflow-auto rounded-lg bg-[var(--bg-inset)] p-4 text-xs">{p.unified_diff}</pre>}</section><section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Before / after proof</h2><div className="mt-3 flex flex-wrap items-center gap-3"><SafetyBadge value={r.before?.classification}/><span>PATCH APPLIED →</span><SafetyBadge value={r.after?.classification}/><b className={r.patch_effective?'text-emerald-400':''}>Patch effective: {r.patch_effective===undefined?'—':String(r.patch_effective)}</b></div>{r.patch_effective===true&&<p className="mt-3 text-sm text-emerald-300">Patch verified: the same attack chain passed after remediation.</p>}</section></div> }
export function Patches() {
 const {id=''}=useParams(); const patch=useApi(()=>getPatch(id),[id]); const result=useApi(()=>getPatchResult(id),[id]); const [busy,setBusy]=useState(false); const [message,setMessage]=useState<string|null>(null)
 const create=()=>{setBusy(true);setMessage(null);generatePatch(id).then(()=>patch.reload()).catch(error=>setMessage(error instanceof Error?error.message:'Could not generate patch.')).finally(()=>setBusy(false))}
 const retest=()=>{setBusy(true);setMessage(null);retestPatch(id).then(()=>result.reload()).catch(error=>setMessage(error instanceof Error?error.message:'Could not retest patch.')).finally(()=>setBusy(false))}
 if(patch.status==='loading'||result.status==='loading')return <LoadingState label="Loading remediation evidence…"/>
 const p=patch.status==='success'?patch.data:null; const r=result.status==='success'?result.data:null
 return <div className="space-y-6"><PageHeader title="Auto-Fix / Prompt Patcher" subtitle={`Remediation evidence for ${id}`} actions={<div className="flex flex-wrap gap-2"><button className="rounded-lg bg-[var(--accent)] px-3 py-2 text-sm text-white disabled:opacity-50" onClick={create} disabled={busy}>{busy?'Working…':'Generate Patch'}</button><button className="rounded-lg border border-[var(--border-strong)] px-3 py-2 text-sm disabled:opacity-50" onClick={retest} disabled={busy||!p}>{busy?'Working…':'Run Re-test'}</button></div>}/>{message&&<ErrorState message={message} onRetry={()=>setMessage(null)}/>} {!p&&patch.status==='error'&&<div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5 text-sm text-[var(--text-muted)]">No patch has been generated for this chain yet. Use Generate Patch to create one from the recorded unsafe classification.</div>}{p&&<><section className="rounded-xl border border-red-500/30 bg-red-500/5 p-5"><h2 className="font-semibold">Failure</h2><div className="mt-2 flex gap-2"><SafetyBadge value={r?.before?.classification}/><SafetyBadge value={p.severity||r?.before?.severity}/><span>Failed turn: {p.failed_turn??r?.before?.failed_turn??'—'}</span></div><p className="mt-3 text-sm text-[var(--text-muted)]">{p.reason||r?.before?.reason||'No failure rationale returned.'}</p></section><section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Generated patch</h2><p className="mt-2 text-sm text-[var(--text-muted)]">{p.vulnerability_analysis||'No vulnerability analysis returned.'}</p><p className="mt-2 text-sm text-[var(--text-muted)]">{p.patch_summary||'No patch summary returned.'}</p><div className="mt-4 grid gap-4 lg:grid-cols-2"><Prompt title="Original prompt" value={p.original_prompt}/><Prompt title="Patched prompt" value={p.patched_prompt}/></div>{p.unified_diff&&<pre className="mt-4 overflow-auto rounded-lg bg-[var(--bg-inset)] p-4 text-xs">{p.unified_diff}</pre>}</section></>}{r&&<section className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5"><h2 className="font-semibold">Before / after proof</h2><div className="mt-3 flex flex-wrap items-center gap-3"><SafetyBadge value={r.before?.classification}/><span>PATCH APPLIED →</span><SafetyBadge value={r.after?.classification}/><SafetyBadge value={r.patch_effective?'effective':'needs review'}/></div><p className="mt-3 text-sm text-[var(--text-muted)]">{r.after?.reason||'No retest rationale returned.'}</p></section>}{!r&&result.status==='error'&&<div className="rounded-xl border border-[var(--border)] bg-[var(--surface)] p-5 text-sm text-[var(--text-muted)]">No retest result exists yet. Generate the patch, then run the re-test.</div>}</div>
}
function Prompt({title,value}:{title:string;value?:string}){return <div><h3 className="mb-2 text-sm font-semibold">{title}</h3><pre className="max-h-80 overflow-auto whitespace-pre-wrap rounded-lg bg-[var(--bg-inset)] p-3 text-xs">{value||'Not returned by backend.'}</pre></div>}
