// Field names below mirror the backend exactly (Backend/data/scenarios.json,
// Backend/data/traces/*.json, Backend/data/classifications/*.json). Category
// and severity are typed as `string`, not string-literal unions: the backend
// vocabulary is generated by an LLM per agent and must not be hardcoded here.

export interface ToolParameterSchema {
    type: string
    properties?: Record<string, { type: string; description?: string }>
    required?: string[]
    [key: string]: unknown
}

export interface Tool {
    name: string
    description: string
    parameters: ToolParameterSchema
}

export interface AgentConfig {
    agent_name: string
    domain: string
    system_prompt: string
    purpose: string
    rules: string[]
    tools: Tool[]
}

export interface Scenario {
    id: string
    category: string
    description: string
    user_input: string
    expected_safe_behavior: string
    severity: string
}

export interface ToolOutput {
    tool_name: string
    status: string
    result: Record<string, unknown>
}

export interface FunctionCallEvent {
    turn: number
    action: 'function_call'
    name: string
    args: Record<string, unknown>
    tool_output: ToolOutput
}

export interface TextResponseEvent {
    turn: number
    action: 'text_response'
    content: string
}

export type TraceEvent = FunctionCallEvent | TextResponseEvent | (Record<string, unknown> & { turn: number; action: string })

export interface MockToolLogEntry {
    sequence: number
    tool_name: string
    arguments: Record<string, unknown>
    outcome: string
    result: Record<string, unknown>
}

export interface TraceExecution {
    status: string
    turns_used: number
    final_response: string
    trace: TraceEvent[]
}

export interface Trace {
    scenario_id: string
    category: string
    severity: string
    description: string
    user_input: string
    expected_safe_behavior: string
    execution: TraceExecution
    mock_tool_log: MockToolLogEntry[]
}

export interface Classification {
    scenario_id?: string
    classification: string // "safe" | "unsafe" in current backend vocabulary
    failure_category: string | null
    severity: string // "none" when safe; low/medium/high/critical (or other) when unsafe
    reason: string
}

export interface ScenarioResult extends Scenario {
    trace: Trace | null
    classification: Classification | null
}

export type RunStatus = 'queued' | 'executing' | 'classifying' | 'completed' | 'failed'

export interface ScenariosStatus {
    scenario_count: number
    stale: boolean
    current_agent_name: string | null
    generated_for_agent_name: string | null
}

export interface RunState {
    id: string
    status: RunStatus
    started_at: string
    finished_at: string | null
    total: number
    executed: number
    classified: number
    errors: string[]
    error: string | null
}

export type GenerationStatus = 'queued' | 'running' | 'completed' | 'failed'

export interface GenerationJob {
    id: string
    status: GenerationStatus
    stage: string | null
    categories_total: number
    categories_done: string[]
    category_errors: Record<string, string>
    scenario_count: number | null
    cleared_stale_results: number | null
    started_at: string
    finished_at: string | null
    error: string | null
}

// Multi-turn safety artifacts are backend-produced. Fields are deliberately
// optional where older result files use alternate names.
export interface GuardrailResult {
    scenario_id: string
    safety_status?: string
    classification?: string
    severity?: string
    target_tool?: string
    attack_vector?: string
    user_input?: string
    expected_safe_behavior?: string
    reason?: string
    judge_explanation?: string
    violation_detected?: boolean
}

export interface AttackChainTurn {
    turn?: number
    user_message?: string
    user_input?: string
    agent_response?: string
    tool_calls?: Array<{ name?: string; tool_name?: string; arguments?: Record<string, unknown>; args?: Record<string, unknown>; result?: unknown }>
    tool_call?: { name?: string; tool_name?: string; arguments?: Record<string, unknown>; args?: Record<string, unknown>; result?: unknown }
    [key: string]: unknown
}

export interface AttackChain {
    chain_id: string
    attack_type?: string
    category?: string
    target_tool?: string
    description?: string
    expected_safe_behavior?: string
    turns?: AttackChainTurn[]
    classification?: string
    severity?: string
    failed_turn?: number | null
}

export interface ChainClassification {
    chain_id: string
    classification: string
    severity?: string
    failure_category?: string | null
    failed_turn?: number | null
    reason?: string
    tool_action?: string
}

export interface ChainTrace {
    chain_id: string
    attack_type?: string
    category?: string
    target_tool?: string
    turns?: AttackChainTurn[]
    execution?: { turns?: AttackChainTurn[] }
}

export interface Patch {
    chain_id: string
    original_prompt?: string
    patched_prompt?: string
    vulnerability_analysis?: string
    patch_summary?: string
    unified_diff?: string
    failure_category?: string
    severity?: string
    failed_turn?: number | null
    reason?: string
}

export interface PatchResult {
    chain_id: string
    before?: ChainClassification
    after?: ChainClassification
    patch?: Patch
    patch_effective?: boolean
}
